name: hanarchive
services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    networks:
      - hanarchive-network
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    networks:
        - hanarchive-network
    image: redis:8-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  api:
    build:
      context: .
      target: builder
    networks:
      - hanarchive-network
    environment:
      - PORT=8000
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    ports:
      - '8000:8000'
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    networks:
      - hanarchive-network
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/code
      - /code/node_modules
    working_dir: /app

  migration:
    networks:
      - hanarchive-network
    build:
      context: ./backend
    command: alembic upgrade head
    depends_on:
      postgres:
        condition: service_healthy

networks:
  hanarchive-network:

volumes:
  postgres_data: